=== AndruhaICE/pearweb/public_html/dtd/channel-1.0.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:ch="http://pear.php.net/channel-1.0"
           targetNamespace="http://pear.php.net/channel-1.0"
           elementFormDefault="qualified">

  <xs:complexType name="function">
   <xs:simpleContent>
    <xs:extension base="xs:string">
     <xs:attribute name="version" use="required">
      <xs:simpleType>
       <xs:restriction base="xs:string">
        <xs:pattern value="[0-9]+\.[0-9]+"/>
       </xs:restriction>
      </xs:simpleType>
     </xs:attribute>
    </xs:extension>
   </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="functions">
    <xs:sequence>
      <xs:element name="function" type="ch:function" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="serverinternals">
   <xs:sequence>
    <xs:element name="xmlrpc" type="ch:functions"/>
    <xs:element name="soap" type="ch:functions" minOccurs="0"/>
   </xs:sequence>
   <xs:attribute name="host" use="required">
     <xs:simpleType>
     <xs:restriction base="xs:string">
      <xs:pattern value="[A-Za-z][a-zA-Z0-9_\.]+"/>
     </xs:restriction>
    </xs:simpleType>
   </xs:attribute>
  </xs:complexType>

  <xs:complexType name="server">
   <xs:sequence>
    <xs:element name="primary" type="ch:serverinternals"/>
    <xs:element name="mirror" type="ch:serverinternals" minOccurs="0" maxOccurs="unbounded"/>
   </xs:sequence>
  </xs:complexType>

  <xs:complexType name="subchannelserver">
   <xs:sequence>
    <xs:element name="xmlrpc" type="ch:functions" minOccurs="0"/>
    <xs:element name="soap" type="ch:functions" minOccurs="0"/>
   </xs:sequence>
  </xs:complexType>

  <xs:complexType name="subchannel">
   <xs:sequence>
    <xs:element name="summary" type="xs:string"/>
    <xs:element name="server" type="ch:subchannelserver"/>
   </xs:sequence>
   <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="validatepackage">
   <xs:simpleContent>
    <xs:extension base="xs:string">
     <xs:attribute name="version" use="required">
      <xs:simpleType>
       <xs:restriction base="xs:string">
        <xs:pattern value="[0-9]+(\.[0-9]+)*([a-zA-Z]+[0-9]*)?"/>
       </xs:restriction>
      </xs:simpleType>
     </xs:attribute>
    </xs:extension>
   </xs:simpleContent>
  </xs:complexType>

  <xs:element name="channel">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="summary" type="xs:string"/>
        <xs:element name="validatepackage" type="ch:validatepackage" minOccurs="0"/>
        <xs:element name="servers" type="ch:server"/>
        <xs:element name="subchannel" type="ch:subchannel" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="version" use="required">
       <xs:simpleType>
        <xs:restriction base="xs:string">
         <xs:pattern value="[0-9]+\.[0-9]+"/>
        </xs:restriction>
       </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AndruhaICE/pearweb/public_html/channel.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<channel version="1.0" xmlns="http://pear.php.net/channel-1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pear.php.net/channel-1.0
http://pear.php.net/dtd/channel-1.0.xsd">
 <name>pear.php.net</name>
 <suggestedalias>pear</suggestedalias>
 <summary>PHP Extension and Application Repository</summary>
 <servers>
  <primary>
   <xmlrpc>
    <function version="1.0">logintest</function>
    <function version="1.0">package.listLatestReleases</function>
    <function version="1.0">package.listAll</function>
    <function version="1.0">package.info</function>
    <function version="1.0">package.getDownloadURL</function>
    <function version="1.0">package.getDepDownloadURL</function>
    <function version="1.0">package.search</function>
    <function version="1.0">channel.listAll</function>
   </xmlrpc>
<!--   <rest>
    <baseurl type="package">http://pear.php.net/rest/1.0/package</baseurl>
    <baseurl type="category">http://pear.php.net/rest/1.0/category</baseurl>
   </rest> -->
  </primary>
 </servers>
</channel>
