=== AndruhaICE/pearweb/public_html/dtd/package-2.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by Greg Beaver (The Chiara String Quartet) -->
<xs:schema targetNamespace="http://pear.php.net/dtd/package-2.0" elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns="http://pear.php.net/dtd/package-2.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:task="http://pear.php.net/dtd/tasks-1.0">
 <xs:element name="package">
  <xs:annotation>
   <xs:documentation>PEAR package.xml version 2.0</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:sequence>
    <xs:element ref="name"/>
    <xs:element ref="summary"/>
    <xs:element name="description" type="xs:string"/>
    <xs:element ref="lead" maxOccurs="unbounded"/>
    <xs:element ref="maintainer" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element ref="date"/>
    <xs:element ref="version"/>
    <xs:element ref="license"/>
    <xs:element ref="stability"/>
    <xs:element ref="notes"/>
    <xs:element ref="bundle" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element ref="filelist"/>
    <xs:choice>
     <xs:element ref="php" maxOccurs="unbounded"/>
     <xs:element ref="extsrc" maxOccurs="unbounded"/>
     <xs:element ref="extbin" maxOccurs="unbounded"/>
    </xs:choice>
   </xs:sequence>
   <xs:attribute name="version" type="xs:string" use="required" fixed="2.0"/>
   <xs:attribute name="packager-version" type="xs:string">
    <xs:annotation>
     <xs:documentation>version of PEAR package used to package this release</xs:documentation>
    </xs:annotation>
   </xs:attribute>
  </xs:complexType>
 </xs:element>
 <xs:element name="php" type="release">
  <xs:annotation>
   <xs:documentation>PHP source package (PEAR-style)</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="extsrc" type="extsrcrelease">
  <xs:annotation>
   <xs:documentation>PHP extension source package (PECL-style)</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="extbin" type="extbinrelease">
  <xs:annotation>
   <xs:documentation>PHP extension binary package</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:attributeGroup name="maintainer">
  <xs:annotation>
   <xs:documentation>standard maintainer attributes</xs:documentation>
  </xs:annotation>
  <xs:attribute name="user" type="xs:string" use="required"/>
  <xs:attribute name="email" type="xs:string" use="required"/>
  <xs:attribute name="name" type="xs:string" use="required"/>
  <xs:attribute name="active" use="required">
   <xs:simpleType>
    <xs:restriction base="xs:string">
     <xs:enumeration value="yes"/>
     <xs:enumeration value="no"/>
    </xs:restriction>
   </xs:simpleType>
  </xs:attribute>
 </xs:attributeGroup>
 <xs:element name="lead">
  <xs:annotation>
   <xs:documentation>primary package maintainers</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:attributeGroup ref="maintainer"/>
  </xs:complexType>
 </xs:element>
 <xs:element name="maintainer">
  <xs:annotation>
   <xs:documentation>secondary package maintainers</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:attributeGroup ref="maintainer"/>
   <xs:attribute name="role" use="required">
    <xs:simpleType>
     <xs:restriction base="xs:string">
      <xs:enumeration value="developer"/>
      <xs:enumeration value="contributor"/>
      <xs:enumeration value="helper"/>
     </xs:restriction>
    </xs:simpleType>
   </xs:attribute>
  </xs:complexType>
 </xs:element>
 <xs:complexType name="release">
  <xs:annotation>
   <xs:documentation>generic release</xs:documentation>
  </xs:annotation>
  <xs:sequence>
   <xs:element ref="dependencies"/>
   <xs:element ref="globaltasks" minOccurs="0" maxOccurs="unbounded"/>
   <xs:element name="filelist" type="releasefilelist" minOccurs="0"/>
  </xs:sequence>
  <xs:attribute name="id" type="xs:ID" use="optional"/>
 </xs:complexType>
 <xs:element name="date" type="xs:dateTime">
  <xs:annotation>
   <xs:documentation>release date</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="version">
  <xs:annotation>
   <xs:documentation>release version</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:attribute name="api" type="version" use="required"/>
   <xs:attribute name="package" type="version" use="required"/>
  </xs:complexType>
 </xs:element>
 <xs:simpleType name="version">
  <xs:annotation>
   <xs:documentation>version string regex</xs:documentation>
  </xs:annotation>
  <xs:restriction base="xs:string">
   <xs:pattern value="[0-9]+(\.[0-9]+)*([a-zA-Z]+[0-9]*)?"/>
  </xs:restriction>
 </xs:simpleType>
 <xs:element name="license">
  <xs:annotation>
   <xs:documentation>release license</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:simpleContent>
    <xs:extension base="xs:string">
     <xs:attribute name="uri" type="xs:anyURI"/>
     <xs:attribute name="filesource" type="xs:string"/>
    </xs:extension>
   </xs:simpleContent>
  </xs:complexType>
 </xs:element>
 <xs:element name="stability">
  <xs:annotation>
   <xs:documentation>release stability</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:attributeGroup ref="stability"/>
  </xs:complexType>
 </xs:element>
 <xs:attributeGroup name="stability">
  <xs:annotation>
   <xs:documentation>attributes for stability tag</xs:documentation>
  </xs:annotation>
  <xs:attribute name="api" use="required">
   <xs:simpleType>
    <xs:restriction base="xs:string">
     <xs:enumeration value="devel"/>
     <xs:enumeration value="alpha"/>
     <xs:enumeration value="beta"/>
     <xs:enumeration value="stable"/>
    </xs:restriction>
   </xs:simpleType>
  </xs:attribute>
  <xs:attribute name="package" use="required">
   <xs:simpleType>
    <xs:restriction base="xs:string">
     <xs:enumeration value="snapshot"/>
     <xs:enumeration value="devel"/>
     <xs:enumeration value="alpha"/>
     <xs:enumeration value="beta"/>
     <xs:enumeration value="stable"/>
    </xs:restriction>
   </xs:simpleType>
  </xs:attribute>
 </xs:attributeGroup>
 <xs:element name="notes">
  <xs:annotation>
   <xs:documentation>release notes</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="dependencies" type="dependenciesType">
  <xs:annotation>
   <xs:documentation>release dependencies</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="bundle">
  <xs:annotation>
   <xs:documentation>release package/extension bundles</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:sequence>
    <xs:element name="package" minOccurs="0" maxOccurs="unbounded">
     <xs:complexType>
      <xs:complexContent>
       <xs:extension base="packageDependencyType"/>
      </xs:complexContent>
     </xs:complexType>
    </xs:element>
    <xs:element name="extension" type="extensionDependencyType" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element ref="or" minOccurs="0" maxOccurs="unbounded"/>
   </xs:sequence>
   <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>
 </xs:element>
 <xs:element name="exclude">
  <xs:annotation>
   <xs:documentation>exclude a version</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:attribute name="version" type="version" use="required"/>
  </xs:complexType>
 </xs:element>
 <xs:attributeGroup name="depattributes">
  <xs:annotation>
   <xs:documentation>dependency attributes</xs:documentation>
  </xs:annotation>
  <xs:attribute name="min" type="version"/>
  <xs:attribute name="max" type="version"/>
  <xs:attribute name="recommended" type="version"/>
  <xs:attribute name="optional" default="no">
   <xs:simpleType>
    <xs:restriction base="xs:string">
     <xs:enumeration value="yes"/>
     <xs:enumeration value="no"/>
    </xs:restriction>
   </xs:simpleType>
  </xs:attribute>
 </xs:attributeGroup>
 <xs:complexType name="phpDependencyType">
  <xs:sequence>
   <xs:element ref="exclude" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
  <xs:attributeGroup ref="depattributes"/>
 </xs:complexType>
 <xs:complexType name="packageDependencyType">
  <xs:sequence>
   <xs:element ref="exclude" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
  <xs:attributeGroup ref="depattributes"/>
  <xs:attribute name="channel" type="xs:string" use="required"/>
  <xs:attribute name="name" type="xs:string" use="required"/>
 </xs:complexType>
 <xs:complexType name="extensionDependencyType">
  <xs:sequence>
   <xs:element ref="exclude" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
  <xs:attributeGroup ref="depattributes"/>
  <xs:attribute name="channel" type="xs:string"/>
  <xs:attribute name="name" type="xs:string" use="required"/>
 </xs:complexType>
 <xs:complexType name="sapiDependencyType">
  <xs:sequence>
   <xs:element ref="exclude" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
  <xs:attributeGroup ref="depattributes"/>
  <xs:attribute name="name" type="xs:string" use="required"/>
 </xs:complexType>
 <xs:complexType name="osDependencyType">
  <xs:sequence>
   <xs:element ref="exclude" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
  <xs:attributeGroup ref="depattributes"/>
  <xs:attribute name="name" type="xs:string" use="required"/>
 </xs:complexType>
 <xs:element name="filelist">
  <xs:complexType>
   <xs:sequence>
    <xs:element ref="dir"/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
 <xs:element name="dir">
  <xs:complexType>
   <xs:choice>
    <xs:element ref="dir" maxOccurs="unbounded"/>
    <xs:element ref="file" maxOccurs="unbounded"/>
    <xs:sequence>
     <xs:element ref="dir" maxOccurs="unbounded"/>
     <xs:element ref="file" maxOccurs="unbounded"/>
    </xs:sequence>
   </xs:choice>
   <xs:attribute name="baseinstalldir" type="xs:string"/>
   <xs:attribute name="name" type="xs:string" use="required"/>
   <xs:attribute name="role" type="xs:string"/>
  </xs:complexType>
 </xs:element>
 <xs:element name="file">
  <xs:complexType>
   <xs:choice>
    <xs:any namespace="http://pear.php.net/dtd/tasks-1.0" minOccurs="0" maxOccurs="unbounded"/>
   </xs:choice>
   <xs:attribute name="name" type="xs:string" use="required"/>
   <xs:attribute name="role" type="xs:string" use="required"/>
   <xs:attribute name="install-as" type="xs:string"/>
   <xs:attribute name="baseinstalldir" type="xs:string"/>
   <xs:attribute name="md5sum"/>
   <xs:attribute name="platform"/>
  </xs:complexType>
 </xs:element>
 <xs:element name="globaltasks">
  <xs:annotation>
   <xs:documentation>global installation task</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:sequence>
    <xs:any namespace="http://pear.php.net/dtd/globaltasks-1.0" minOccurs="0" maxOccurs="unbounded"/>
   </xs:sequence>
   <xs:attribute name="type" type="xs:string" use="required"/>
   <xs:anyAttribute namespace="##any"/>
  </xs:complexType>
 </xs:element>
 <xs:complexType name="phprelease">
  <xs:complexContent>
   <xs:extension base="release">
    <xs:sequence>
     <xs:element ref="filelist"/>
    </xs:sequence>
   </xs:extension>
  </xs:complexContent>
 </xs:complexType>
 <xs:complexType name="extsrcrelease">
  <xs:complexContent>
   <xs:extension base="release">
    <xs:sequence>
     <xs:element ref="configureoption" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
   </xs:extension>
  </xs:complexContent>
 </xs:complexType>
 <xs:complexType name="extbinrelease">
  <xs:complexContent>
   <xs:extension base="release">
    <xs:sequence>
     <xs:element ref="configureoption" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
   </xs:extension>
  </xs:complexContent>
 </xs:complexType>
 <xs:element name="configureoption">
  <xs:complexType>
   <xs:attribute name="name" type="xs:string" use="required"/>
   <xs:attribute name="default" type="xs:string"/>
   <xs:attribute name="prompt" type="xs:string" use="required"/>
  </xs:complexType>
 </xs:element>
 <xs:element name="summary" type="xs:string"/>
 <xs:element name="name">
  <xs:complexType>
   <xs:simpleContent>
    <xs:extension base="xs:string">
     <xs:attribute name="channel" type="xs:string" use="required"/>
    </xs:extension>
   </xs:simpleContent>
  </xs:complexType>
 </xs:element>
 <xs:complexType name="releasefilelist">
  <xs:annotation>
   <xs:documentation>filelist for differing between releases</xs:documentation>
  </xs:annotation>
  <xs:sequence>
   <xs:element name="dir">
    <xs:complexType>
     <xs:complexContent>
      <xs:extension base="releasedir"/>
     </xs:complexContent>
    </xs:complexType>
   </xs:element>
  </xs:sequence>
 </xs:complexType>
 <xs:complexType name="releasedir">
  <xs:choice>
   <xs:element name="dir" maxOccurs="unbounded">
    <xs:complexType>
     <xs:complexContent>
      <xs:extension base="releasedir"/>
     </xs:complexContent>
    </xs:complexType>
   </xs:element>
   <xs:choice maxOccurs="unbounded">
    <xs:element name="file">
     <xs:complexType>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="install-as" type="xs:string"/>
     </xs:complexType>
    </xs:element>
    <xs:element name="ignorefile">
     <xs:complexType>
      <xs:attribute name="name" type="xs:string" use="required"/>
     </xs:complexType>
    </xs:element>
   </xs:choice>
   <xs:sequence maxOccurs="unbounded">
    <xs:element name="dir" maxOccurs="unbounded">
     <xs:complexType>
      <xs:complexContent>
       <xs:extension base="releasedir"/>
      </xs:complexContent>
     </xs:complexType>
    </xs:element>
    <xs:choice maxOccurs="unbounded">
     <xs:element name="file">
      <xs:complexType>
       <xs:attribute name="name" use="required">
        <xs:simpleType>
         <xs:restriction base="xs:string">
          <xs:enumeration value="yes"/>
          <xs:enumeration value="no"/>
         </xs:restriction>
        </xs:simpleType>
       </xs:attribute>
       <xs:attribute name="install-as" type="xs:string"/>
      </xs:complexType>
     </xs:element>
     <xs:element name="ignorefile">
      <xs:complexType>
       <xs:attribute name="name" type="xs:string" use="required"/>
      </xs:complexType>
     </xs:element>
    </xs:choice>
   </xs:sequence>
  </xs:choice>
  <xs:attribute name="name" type="xs:string" use="required"/>
 </xs:complexType>
 <xs:complexType name="dependenciesType">
  <xs:sequence>
   <xs:element name="php" type="phpDependencyType">
    <xs:annotation>
     <xs:documentation>PHP version dependency</xs:documentation>
    </xs:annotation>
   </xs:element>
   <xs:element name="package" minOccurs="0" maxOccurs="unbounded">
    <xs:annotation>
     <xs:documentation>PHP package dependency</xs:documentation>
    </xs:annotation>
    <xs:complexType>
     <xs:complexContent>
      <xs:extension base="packageDependencyType">
       <xs:attribute name="subpackage" default="no">
        <xs:simpleType>
         <xs:restriction base="xs:string">
          <xs:enumeration value="yes"/>
          <xs:enumeration value="no"/>
         </xs:restriction>
        </xs:simpleType>
       </xs:attribute>
      </xs:extension>
     </xs:complexContent>
    </xs:complexType>
   </xs:element>
   <xs:element name="extension" minOccurs="0" maxOccurs="unbounded">
    <xs:annotation>
     <xs:documentation>PHP extension dependency</xs:documentation>
    </xs:annotation>
    <xs:complexType>
     <xs:complexContent>
      <xs:extension base="extensionDependencyType"/>
     </xs:complexContent>
    </xs:complexType>
   </xs:element>
   <xs:element name="sapi" minOccurs="0" maxOccurs="unbounded">
    <xs:annotation>
     <xs:documentation>PHP executable type - is this really practical?</xs:documentation>
    </xs:annotation>
    <xs:complexType>
     <xs:complexContent>
      <xs:extension base="sapiDependencyType"/>
     </xs:complexContent>
    </xs:complexType>
   </xs:element>
   <xs:element name="os" type="osDependencyType" minOccurs="0" maxOccurs="unbounded">
    <xs:annotation>
     <xs:documentation>operating system dependency</xs:documentation>
    </xs:annotation>
   </xs:element>
   <xs:element ref="or" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
 </xs:complexType>
 <xs:element name="or">
  <xs:complexType>
   <xs:choice minOccurs="2" maxOccurs="unbounded">
    <xs:element name="package" type="packageDependencyType"/>
    <xs:element name="extension" type="extensionDependencyType"/>
   </xs:choice>
  </xs:complexType>
 </xs:element>
</xs:schema>

=== AndruhaICE/pearweb/package-pepr.xml
<?xml version="1.0" encoding="UTF-8"?>
<package packagerversion="1.9.1" version="2.0" xmlns="http://pear.php.net/dtd/package-2.0" xmlns:tasks="http://pear.php.net/dtd/tasks-1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pear.php.net/dtd/tasks-1.0                              http://pear.php.net/dtd/tasks-1.0.xsd                              http://pear.php.net/dtd/package-2.0                              http://pear.php.net/dtd/package-2.0.xsd">
 <name>pearweb_pepr</name>
 <channel>pear.php.net</channel>
 <summary>The source code for the PEAR website package voting</summary>
 <description>The pearweb_pepr package contains backend and frontend code
 for the package voting part of pearweb as well as the layout for it</description>
 <lead>
  <name>Martin Jansen</name>
  <user>mj</user>
  <email>mj@php.net</email>
  <active>yes</active>
 </lead>
 <lead>
  <name>Greg Beaver</name>
  <user>cellog</user>
  <email>cellog@php.net</email>
  <active>yes</active>
 </lead>
 <lead>
  <name>David Coallier</name>
  <user>davidc</user>
  <email>davidc@php.net</email>
  <active>yes</active>
 </lead>
 <lead>
  <name>Pierre-Alain Joye</name>
  <user>pajoye</user>
  <email>pajoye@php.net</email>
  <active>no</active>
 </lead>
 <lead>
  <name>Helgi Thormar</name>
  <user>dufuz</user>
  <email>dufuz@php.net</email>
  <active>yes</active>
 </lead>
 <developer>
  <name>Stig Bakken</name>
  <user>ssb</user>
  <email>stig@php.net</email>
  <active>no</active>
 </developer>
 <developer>
  <name>Tomas V.V.Cox</name>
  <user>cox</user>
  <email>cox@idecnet.com</email>
  <active>no</active>
 </developer>
 <developer>
  <name>Daniel Convissor</name>
  <user>danielc</user>
  <email>danielc@php.net</email>
  <active>no</active>
 </developer>
 <developer>
  <name>Tobias Schlitt</name>
  <user>toby</user>
  <email>toby@php.net</email>
  <active>no</active>
 </developer>
 <developer>
  <name>Christian Weiske</name>
  <user>cweiske</user>
  <email>cweiske@php.net</email>
  <active>yes</active>
 </developer>
 <developer>
  <name>Mark Wiesemann</name>
  <user>wiesemann</user>
  <email>wiesemann@php.net</email>
  <active>yes</active>
 </developer>
 <date>2011-04-13</date>
 <time>20:36:56</time>
 <version>
  <release>1.0.4</release>
  <api>0.1.0</api>
 </version>
 <stability>
  <release>stable</release>
  <api>stable</api>
 </stability>
 <license uri="http://www.php.net/license">PHP License</license>
 <notes>
- Migration to QF2 for everything but pepr-proposal-editing [clockwerx]
- Remove BBCode (in favour of only supporting Text_Wiki from now on) [till]
- Small refactoring while debugging [till]
- Fix Bug #16578 Unable to use https URL in &quot;Links&quot; section [saltybeagle]
 </notes>
 <contents>
  <dir baseinstalldir="/pear.php.net/" name="/">
   <dir name="cron">
    <file name="pepr.php" role="www" />
   </dir> <!-- /cron -->
   <dir name="include">
    <dir name="pepr">
     <file name="pepr-emails.php" role="www" />
     <file name="pepr-ppcomment.php" role="www" />
     <file name="pepr-pplink.php" role="www" />
     <file name="pepr-ppvote.php" role="www" />
     <file name="pepr-proposal.php" role="www" />
     <file name="pepr.php" role="www" />
    </dir> <!-- /include/pepr -->
   </dir> <!-- /include -->
   <dir name="public_html">
    <dir name="pepr">
     <file name="index.php" role="www" />
     <file name="pepr-bbcode-help.php" role="www" />
     <file name="pepr-comments-show.php" role="www" />
     <file name="pepr-proposal-delete.php" role="www" />
     <file name="pepr-proposal-edit.php" role="www" />
     <file name="pepr-proposal-show.php" role="www" />
     <file name="pepr-qa-stats.php" role="www" />
     <file name="pepr-vote-show.php" role="www" />
     <file name="pepr-votes-show.php" role="www" />
    </dir> <!-- /public_html/pepr -->
   </dir> <!-- /public_html -->
   <dir name="sql">
    <file name="pearweb_pepr.xml" role="www" />
   </dir> <!-- /sql -->
  </dir> <!-- / -->
 </contents>
 <dependencies>
  <required>
   <php>
    <min>5.2.3</min>
   </php>
   <pearinstaller>
    <min>1.7.1</min>
   </pearinstaller>
   <package>
    <name>PEAR</name>
    <channel>pear.php.net</channel>
    <min>1.7.1</min>
   </package>
   <package>
    <name>HTML_QuickForm</name>
    <channel>pear.php.net</channel>
    <min>3.2.12</min>
   </package>
   <package>
    <name>HTML_QuickForm2</name>
    <channel>pear.php.net</channel>
    <min>0.5.3</min>
   </package>
   <package>
    <name>pearweb</name>
    <channel>pear.php.net</channel>
    <min>1.18.0</min>
   </package>
   <package>
    <name>Text_Wiki</name>
    <channel>pear.php.net</channel>
    <min>1.2.0</min>
   </package>
   <extension>
    <name>pcre</name>
   </extension>
   <extension>
    <name>mysqli</name>
   </extension>
  </required>
 </dependencies>
 <phprelease />
 <changelog>
  <release>
   <version>
    <release>1.0.0</release>
    <api>0.1.0</api>
   </version>
   <stability>
    <release>stable</release>
    <api>stable</api>
   </stability>
   <date>2009-04-28</date>
   <license uri="http://www.php.net/license">PHP License</license>
   <notes>
- split the pepr code from pearweb [dufuz]
   </notes>
  </release>
  <release>
   <version>
    <release>1.0.1</release>
    <api>0.1.0</api>
   </version>
   <stability>
    <release>stable</release>
    <api>stable</api>
   </stability>
   <date>2009-04-29</date>
   <license uri="http://www.php.net/license">PHP License</license>
   <notes>
- Remove include/Damblan/Search/PEPr.php since it should be in the main package
   </notes>
  </release>
  <release>
   <version>
    <release>1.0.2</release>
    <api>0.1.0</api>
   </version>
   <stability>
    <release>stable</release>
    <api>stable</api>
   </stability>
   <date>2009-06-20</date>
   <license uri="http://www.php.net/license">PHP License</license>
   <notes>
Refactored RSS feeds for bugs
Changed RSS feeds for homepage
Individual bugs now render Baetle (RDF)
Improved homepage to focus on the human side(s) of PEAR
   </notes>
  </release>
  <release>
   <version>
    <release>1.0.3</release>
    <api>0.1.0</api>
   </version>
   <stability>
    <release>stable</release>
    <api>stable</api>
   </stability>
   <date>2009-09-07</date>
   <license uri="http://www.php.net/license">PHP License</license>
   <notes>
- Remove date_format which caused pepr proposals to be stuck forever [bbieber]
- Fix HTML errors [cweiske]
- Fix bug #16410: Rejected PEPr proposals should not steal names [clockwerx]
- Dropped restrictions around &quot;the same user must be the re-proposer&quot; [clockwerx]
   </notes>
  </release>
  <release>
   <version>
    <release>1.0.4</release>
    <api>0.1.0</api>
   </version>
   <stability>
    <release>stable</release>
    <api>stable</api>
   </stability>
   <date>2011-04-13</date>
   <license uri="http://www.php.net/license">PHP License</license>
   <notes>
- Migration to QF2 for everything but pepr-proposal-editing [clockwerx]
- Remove BBCode (in favour of only supporting Text_Wiki from now on) [till]
- Small refactoring while debugging [till]
- Fix Bug #16578 Unable to use https URL in &quot;Links&quot; section [saltybeagle]
   </notes>
  </release>
 </changelog>
</package>

=== AndruhaICE/pearweb/package-election.xml
<?xml version="1.0" encoding="UTF-8"?>
<package packagerversion="1.8.0alpha1" version="2.0" xmlns="http://pear.php.net/dtd/package-2.0" xmlns:tasks="http://pear.php.net/dtd/tasks-1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pear.php.net/dtd/tasks-1.0                              http://pear.php.net/dtd/tasks-1.0.xsd                              http://pear.php.net/dtd/package-2.0                              http://pear.php.net/dtd/package-2.0.xsd">
 <name>pearweb_election</name>
 <channel>pear.php.net</channel>
 <summary>The source code for the PEAR website election</summary>
 <description>The pearweb_election package contains backend and frontend code
 for the election part of pearweb as well as the layout for it</description>
 <lead>
  <name>Martin Jansen</name>
  <user>mj</user>
  <email>mj@php.net</email>
  <active>yes</active>
 </lead>
 <lead>
  <name>Greg Beaver</name>
  <user>cellog</user>
  <email>cellog@php.net</email>
  <active>yes</active>
 </lead>
 <lead>
  <name>David Coallier</name>
  <user>davidc</user>
  <email>davidc@php.net</email>
  <active>yes</active>
 </lead>
 <lead>
  <name>Pierre-Alain Joye</name>
  <user>pajoye</user>
  <email>pajoye@php.net</email>
  <active>no</active>
 </lead>
 <lead>
  <name>Helgi Thormar</name>
  <user>dufuz</user>
  <email>dufuz@php.net</email>
  <active>yes</active>
 </lead>
 <developer>
  <name>Stig Bakken</name>
  <user>ssb</user>
  <email>stig@php.net</email>
  <active>no</active>
 </developer>
 <developer>
  <name>Tomas V.V.Cox</name>
  <user>cox</user>
  <email>cox@idecnet.com</email>
  <active>no</active>
 </developer>
 <developer>
  <name>Daniel Convissor</name>
  <user>danielc</user>
  <email>danielc@php.net</email>
  <active>no</active>
 </developer>
 <developer>
  <name>Tobias Schlitt</name>
  <user>toby</user>
  <email>toby@php.net</email>
  <active>no</active>
 </developer>
 <developer>
  <name>Christian Weiske</name>
  <user>cweiske</user>
  <email>cweiske@php.net</email>
  <active>yes</active>
 </developer>
 <developer>
  <name>Mark Wiesemann</name>
  <user>wiesemann</user>
  <email>wiesemann@php.net</email>
  <active>yes</active>
 </developer>
 <date>2009-01-02</date>
 <time>04:33:37</time>
 <version>
  <release>1.0.0</release>
  <api>0.1.0</api>
 </version>
 <stability>
  <release>stable</release>
  <api>stable</api>
 </stability>
 <license uri="http://www.php.net/license">PHP License</license>
 <notes>
- split the election code from pearweb [dufuz]
 </notes>
 <contents>
  <dir baseinstalldir="/" name="/">
   <dir name="cron">
    <file name="election_results.php" role="www" />
   </dir> <!-- /cron -->
   <dir name="include">
    <dir name="election">
     <file name="pear-election-accountrequest.php" role="www" />
     <file name="pear-election.php" role="www" />
     <file name="pear-voter.php" role="www" />
    </dir> <!-- /include/election -->
   </dir> <!-- /include -->
   <dir name="public_html">
    <dir name="election">
     <file name="edit.php" role="www" />
     <file name="index.php" role="www" />
     <file name="info.php" role="www" />
     <file name="new.php" role="www" />
    </dir> <!-- /public_html/election -->
   </dir> <!-- /public_html -->
   <dir name="sql">
    <file name="pearweb_election.xml" role="www" />
   </dir> <!-- /sql -->
   <dir name="templates">
    <dir name="election">
     <file name="confirm.tpl.php" role="www" />
     <file name="confirmed.tpl.php" role="www" />
     <file name="dovote.tpl.php" role="www" />
     <file name="listforedit.tpl.php" role="www" />
     <file name="new-step1.tpl.php" role="www" />
     <file name="new-step2.tpl.php" role="www" />
     <file name="new-step3.tpl.php" role="www" />
     <file name="pending.tpl.php" role="www" />
     <file name="register.tpl.php" role="www" />
     <file name="results.tpl.php" role="www" />
     <file name="showresults.tpl.php" role="www" />
     <file name="vote.tpl.php" role="www" />
    </dir> <!-- /templates/election -->
   </dir> <!-- /templates -->
  </dir> <!-- / -->
 </contents>
 <dependencies>
  <required>
   <php>
    <min>5.2.3</min>
   </php>
   <pearinstaller>
    <min>1.7.1</min>
   </pearinstaller>
   <package>
    <name>PEAR</name>
    <channel>pear.php.net</channel>
    <min>1.7.1</min>
   </package>
   <package>
    <name>pearweb</name>
    <channel>pear.php.net</channel>
    <min>1.18.0</min>
   </package>
   <package>
    <name>Text_Wiki</name>
    <channel>pear.php.net</channel>
    <min>1.2.0</min>
   </package>
   <extension>
    <name>pcre</name>
   </extension>
   <extension>
    <name>mysqli</name>
   </extension>
  </required>
 </dependencies>
 <phprelease />
 <changelog>
  <release>
   <version>
    <release>1.0.0</release>
    <api>0.1.0</api>
   </version>
   <stability>
    <release>stable</release>
    <api>stable</api>
   </stability>
   <date>2009-01-02</date>
   <license uri="http://www.php.net/license">PHP License</license>
   <notes>
- split the election code from pearweb [dufuz]
   </notes>
  </release>
 </changelog>
</package>
