=== AndruhaICE/pearweb/public_html/dtd/package-2.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by Greg Beaver (The Chiara String Quartet) -->
<xs:schema targetNamespace="http://pear.php.net/dtd/package-2.0" elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns="http://pear.php.net/dtd/package-2.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:task="http://pear.php.net/dtd/tasks-1.0">
 <xs:element name="package">
  <xs:annotation>
   <xs:documentation>PEAR package.xml version 2.0</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:sequence>
    <xs:element ref="name"/>
    <xs:element ref="summary"/>
    <xs:element name="description" type="xs:string"/>
    <xs:element ref="lead" maxOccurs="unbounded"/>
    <xs:element ref="maintainer" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element ref="date"/>
    <xs:element ref="version"/>
    <xs:element ref="license"/>
    <xs:element ref="stability"/>
    <xs:element ref="notes"/>
    <xs:element ref="bundle" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element ref="filelist"/>
    <xs:choice>
     <xs:element ref="php" maxOccurs="unbounded"/>
     <xs:element ref="extsrc" maxOccurs="unbounded"/>
     <xs:element ref="extbin" maxOccurs="unbounded"/>
    </xs:choice>
   </xs:sequence>
   <xs:attribute name="version" type="xs:string" use="required" fixed="2.0"/>
   <xs:attribute name="packager-version" type="xs:string">
    <xs:annotation>
     <xs:documentation>version of PEAR package used to package this release</xs:documentation>
    </xs:annotation>
   </xs:attribute>
  </xs:complexType>
 </xs:element>
 <xs:element name="php" type="release">
  <xs:annotation>
   <xs:documentation>PHP source package (PEAR-style)</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="extsrc" type="extsrcrelease">
  <xs:annotation>
   <xs:documentation>PHP extension source package (PECL-style)</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="extbin" type="extbinrelease">
  <xs:annotation>
   <xs:documentation>PHP extension binary package</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:attributeGroup name="maintainer">
  <xs:annotation>
   <xs:documentation>standard maintainer attributes</xs:documentation>
  </xs:annotation>
  <xs:attribute name="user" type="xs:string" use="required"/>
  <xs:attribute name="email" type="xs:string" use="required"/>
  <xs:attribute name="name" type="xs:string" use="required"/>
  <xs:attribute name="active" use="required">
   <xs:simpleType>
    <xs:restriction base="xs:string">
     <xs:enumeration value="yes"/>
     <xs:enumeration value="no"/>
    </xs:restriction>
   </xs:simpleType>
  </xs:attribute>
 </xs:attributeGroup>
 <xs:element name="lead">
  <xs:annotation>
   <xs:documentation>primary package maintainers</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:attributeGroup ref="maintainer"/>
  </xs:complexType>
 </xs:element>
 <xs:element name="maintainer">
  <xs:annotation>
   <xs:documentation>secondary package maintainers</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:attributeGroup ref="maintainer"/>
   <xs:attribute name="role" use="required">
    <xs:simpleType>
     <xs:restriction base="xs:string">
      <xs:enumeration value="developer"/>
      <xs:enumeration value="contributor"/>
      <xs:enumeration value="helper"/>
     </xs:restriction>
    </xs:simpleType>
   </xs:attribute>
  </xs:complexType>
 </xs:element>
 <xs:complexType name="release">
  <xs:annotation>
   <xs:documentation>generic release</xs:documentation>
  </xs:annotation>
  <xs:sequence>
   <xs:element ref="dependencies"/>
   <xs:element ref="globaltasks" minOccurs="0" maxOccurs="unbounded"/>
   <xs:element name="filelist" type="releasefilelist" minOccurs="0"/>
  </xs:sequence>
  <xs:attribute name="id" type="xs:ID" use="optional"/>
 </xs:complexType>
 <xs:element name="date" type="xs:dateTime">
  <xs:annotation>
   <xs:documentation>release date</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="version">
  <xs:annotation>
   <xs:documentation>release version</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:attribute name="api" type="version" use="required"/>
   <xs:attribute name="package" type="version" use="required"/>
  </xs:complexType>
 </xs:element>
 <xs:simpleType name="version">
  <xs:annotation>
   <xs:documentation>version string regex</xs:documentation>
  </xs:annotation>
  <xs:restriction base="xs:string">
   <xs:pattern value="[0-9]+(\.[0-9]+)*([a-zA-Z]+[0-9]*)?"/>
  </xs:restriction>
 </xs:simpleType>
 <xs:element name="license">
  <xs:annotation>
   <xs:documentation>release license</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:simpleContent>
    <xs:extension base="xs:string">
     <xs:attribute name="uri" type="xs:anyURI"/>
     <xs:attribute name="filesource" type="xs:string"/>
    </xs:extension>
   </xs:simpleContent>
  </xs:complexType>
 </xs:element>
 <xs:element name="stability">
  <xs:annotation>
   <xs:documentation>release stability</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:attributeGroup ref="stability"/>
  </xs:complexType>
 </xs:element>
 <xs:attributeGroup name="stability">
  <xs:annotation>
   <xs:documentation>attributes for stability tag</xs:documentation>
  </xs:annotation>
  <xs:attribute name="api" use="required">
   <xs:simpleType>
    <xs:restriction base="xs:string">
     <xs:enumeration value="devel"/>
     <xs:enumeration value="alpha"/>
     <xs:enumeration value="beta"/>
     <xs:enumeration value="stable"/>
    </xs:restriction>
   </xs:simpleType>
  </xs:attribute>
  <xs:attribute name="package" use="required">
   <xs:simpleType>
    <xs:restriction base="xs:string">
     <xs:enumeration value="snapshot"/>
     <xs:enumeration value="devel"/>
     <xs:enumeration value="alpha"/>
     <xs:enumeration value="beta"/>
     <xs:enumeration value="stable"/>
    </xs:restriction>
   </xs:simpleType>
  </xs:attribute>
 </xs:attributeGroup>
 <xs:element name="notes">
  <xs:annotation>
   <xs:documentation>release notes</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="dependencies" type="dependenciesType">
  <xs:annotation>
   <xs:documentation>release dependencies</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="bundle">
  <xs:annotation>
   <xs:documentation>release package/extension bundles</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:sequence>
    <xs:element name="package" minOccurs="0" maxOccurs="unbounded">
     <xs:complexType>
      <xs:complexContent>
       <xs:extension base="packageDependencyType"/>
      </xs:complexContent>
     </xs:complexType>
    </xs:element>
    <xs:element name="extension" type="extensionDependencyType" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element ref="or" minOccurs="0" maxOccurs="unbounded"/>
   </xs:sequence>
   <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>
 </xs:element>
 <xs:element name="exclude">
  <xs:annotation>
   <xs:documentation>exclude a version</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:attribute name="version" type="version" use="required"/>
  </xs:complexType>
 </xs:element>
 <xs:attributeGroup name="depattributes">
  <xs:annotation>
   <xs:documentation>dependency attributes</xs:documentation>
  </xs:annotation>
  <xs:attribute name="min" type="version"/>
  <xs:attribute name="max" type="version"/>
  <xs:attribute name="recommended" type="version"/>
  <xs:attribute name="optional" default="no">
   <xs:simpleType>
    <xs:restriction base="xs:string">
     <xs:enumeration value="yes"/>
     <xs:enumeration value="no"/>
    </xs:restriction>
   </xs:simpleType>
  </xs:attribute>
 </xs:attributeGroup>
 <xs:complexType name="phpDependencyType">
  <xs:sequence>
   <xs:element ref="exclude" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
  <xs:attributeGroup ref="depattributes"/>
 </xs:complexType>
 <xs:complexType name="packageDependencyType">
  <xs:sequence>
   <xs:element ref="exclude" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
  <xs:attributeGroup ref="depattributes"/>
  <xs:attribute name="channel" type="xs:string" use="required"/>
  <xs:attribute name="name" type="xs:string" use="required"/>
 </xs:complexType>
 <xs:complexType name="extensionDependencyType">
  <xs:sequence>
   <xs:element ref="exclude" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
  <xs:attributeGroup ref="depattributes"/>
  <xs:attribute name="channel" type="xs:string"/>
  <xs:attribute name="name" type="xs:string" use="required"/>
 </xs:complexType>
 <xs:complexType name="sapiDependencyType">
  <xs:sequence>
   <xs:element ref="exclude" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
  <xs:attributeGroup ref="depattributes"/>
  <xs:attribute name="name" type="xs:string" use="required"/>
 </xs:complexType>
 <xs:complexType name="osDependencyType">
  <xs:sequence>
   <xs:element ref="exclude" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
  <xs:attributeGroup ref="depattributes"/>
  <xs:attribute name="name" type="xs:string" use="required"/>
 </xs:complexType>
 <xs:element name="filelist">
  <xs:complexType>
   <xs:sequence>
    <xs:element ref="dir"/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
 <xs:element name="dir">
  <xs:complexType>
   <xs:choice>
    <xs:element ref="dir" maxOccurs="unbounded"/>
    <xs:element ref="file" maxOccurs="unbounded"/>
    <xs:sequence>
     <xs:element ref="dir" maxOccurs="unbounded"/>
     <xs:element ref="file" maxOccurs="unbounded"/>
    </xs:sequence>
   </xs:choice>
   <xs:attribute name="baseinstalldir" type="xs:string"/>
   <xs:attribute name="name" type="xs:string" use="required"/>
   <xs:attribute name="role" type="xs:string"/>
  </xs:complexType>
 </xs:element>
 <xs:element name="file">
  <xs:complexType>
   <xs:choice>
    <xs:any namespace="http://pear.php.net/dtd/tasks-1.0" minOccurs="0" maxOccurs="unbounded"/>
   </xs:choice>
   <xs:attribute name="name" type="xs:string" use="required"/>
   <xs:attribute name="role" type="xs:string" use="required"/>
   <xs:attribute name="install-as" type="xs:string"/>
   <xs:attribute name="baseinstalldir" type="xs:string"/>
   <xs:attribute name="md5sum"/>
   <xs:attribute name="platform"/>
  </xs:complexType>
 </xs:element>
 <xs:element name="globaltasks">
  <xs:annotation>
   <xs:documentation>global installation task</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:sequence>
    <xs:any namespace="http://pear.php.net/dtd/globaltasks-1.0" minOccurs="0" maxOccurs="unbounded"/>
   </xs:sequence>
   <xs:attribute name="type" type="xs:string" use="required"/>
   <xs:anyAttribute namespace="##any"/>
  </xs:complexType>
 </xs:element>
 <xs:complexType name="phprelease">
  <xs:complexContent>
   <xs:extension base="release">
    <xs:sequence>
     <xs:element ref="filelist"/>
    </xs:sequence>
   </xs:extension>
  </xs:complexContent>
 </xs:complexType>
 <xs:complexType name="extsrcrelease">
  <xs:complexContent>
   <xs:extension base="release">
    <xs:sequence>
     <xs:element ref="configureoption" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
   </xs:extension>
  </xs:complexContent>
 </xs:complexType>
 <xs:complexType name="extbinrelease">
  <xs:complexContent>
   <xs:extension base="release">
    <xs:sequence>
     <xs:element ref="configureoption" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
   </xs:extension>
  </xs:complexContent>
 </xs:complexType>
 <xs:element name="configureoption">
  <xs:complexType>
   <xs:attribute name="name" type="xs:string" use="required"/>
   <xs:attribute name="default" type="xs:string"/>
   <xs:attribute name="prompt" type="xs:string" use="required"/>
  </xs:complexType>
 </xs:element>
 <xs:element name="summary" type="xs:string"/>
 <xs:element name="name">
  <xs:complexType>
   <xs:simpleContent>
    <xs:extension base="xs:string">
     <xs:attribute name="channel" type="xs:string" use="required"/>
    </xs:extension>
   </xs:simpleContent>
  </xs:complexType>
 </xs:element>
 <xs:complexType name="releasefilelist">
  <xs:annotation>
   <xs:documentation>filelist for differing between releases</xs:documentation>
  </xs:annotation>
  <xs:sequence>
   <xs:element name="dir">
    <xs:complexType>
     <xs:complexContent>
      <xs:extension base="releasedir"/>
     </xs:complexContent>
    </xs:complexType>
   </xs:element>
  </xs:sequence>
 </xs:complexType>
 <xs:complexType name="releasedir">
  <xs:choice>
   <xs:element name="dir" maxOccurs="unbounded">
    <xs:complexType>
     <xs:complexContent>
      <xs:extension base="releasedir"/>
     </xs:complexContent>
    </xs:complexType>
   </xs:element>
   <xs:choice maxOccurs="unbounded">
    <xs:element name="file">
     <xs:complexType>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="install-as" type="xs:string"/>
     </xs:complexType>
    </xs:element>
    <xs:element name="ignorefile">
     <xs:complexType>
      <xs:attribute name="name" type="xs:string" use="required"/>
     </xs:complexType>
    </xs:element>
   </xs:choice>
   <xs:sequence maxOccurs="unbounded">
    <xs:element name="dir" maxOccurs="unbounded">
     <xs:complexType>
      <xs:complexContent>
       <xs:extension base="releasedir"/>
      </xs:complexContent>
     </xs:complexType>
    </xs:element>
    <xs:choice maxOccurs="unbounded">
     <xs:element name="file">
      <xs:complexType>
       <xs:attribute name="name" use="required">
        <xs:simpleType>
         <xs:restriction base="xs:string">
          <xs:enumeration value="yes"/>
          <xs:enumeration value="no"/>
         </xs:restriction>
        </xs:simpleType>
       </xs:attribute>
       <xs:attribute name="install-as" type="xs:string"/>
      </xs:complexType>
     </xs:element>
     <xs:element name="ignorefile">
      <xs:complexType>
       <xs:attribute name="name" type="xs:string" use="required"/>
      </xs:complexType>
     </xs:element>
    </xs:choice>
   </xs:sequence>
  </xs:choice>
  <xs:attribute name="name" type="xs:string" use="required"/>
 </xs:complexType>
 <xs:complexType name="dependenciesType">
  <xs:sequence>
   <xs:element name="php" type="phpDependencyType">
    <xs:annotation>
     <xs:documentation>PHP version dependency</xs:documentation>
    </xs:annotation>
   </xs:element>
   <xs:element name="package" minOccurs="0" maxOccurs="unbounded">
    <xs:annotation>
     <xs:documentation>PHP package dependency</xs:documentation>
    </xs:annotation>
    <xs:complexType>
     <xs:complexContent>
      <xs:extension base="packageDependencyType">
       <xs:attribute name="subpackage" default="no">
        <xs:simpleType>
         <xs:restriction base="xs:string">
          <xs:enumeration value="yes"/>
          <xs:enumeration value="no"/>
         </xs:restriction>
        </xs:simpleType>
       </xs:attribute>
      </xs:extension>
     </xs:complexContent>
    </xs:complexType>
   </xs:element>
   <xs:element name="extension" minOccurs="0" maxOccurs="unbounded">
    <xs:annotation>
     <xs:documentation>PHP extension dependency</xs:documentation>
    </xs:annotation>
    <xs:complexType>
     <xs:complexContent>
      <xs:extension base="extensionDependencyType"/>
     </xs:complexContent>
    </xs:complexType>
   </xs:element>
   <xs:element name="sapi" minOccurs="0" maxOccurs="unbounded">
    <xs:annotation>
     <xs:documentation>PHP executable type - is this really practical?</xs:documentation>
    </xs:annotation>
    <xs:complexType>
     <xs:complexContent>
      <xs:extension base="sapiDependencyType"/>
     </xs:complexContent>
    </xs:complexType>
   </xs:element>
   <xs:element name="os" type="osDependencyType" minOccurs="0" maxOccurs="unbounded">
    <xs:annotation>
     <xs:documentation>operating system dependency</xs:documentation>
    </xs:annotation>
   </xs:element>
   <xs:element ref="or" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
 </xs:complexType>
 <xs:element name="or">
  <xs:complexType>
   <xs:choice minOccurs="2" maxOccurs="unbounded">
    <xs:element name="package" type="packageDependencyType"/>
    <xs:element name="extension" type="extensionDependencyType"/>
   </xs:choice>
  </xs:complexType>
 </xs:element>
</xs:schema>

=== AndruhaICE/pearweb/package-index.xml
<?xml version="1.0" encoding="UTF-8"?>
<package packagerversion="1.5.4" version="2.0" xmlns="http://pear.php.net/dtd/package-2.0" xmlns:tasks="http://pear.php.net/dtd/tasks-1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pear.php.net/dtd/tasks-1.0                              http://pear.php.net/dtd/tasks-1.0.xsd                              http://pear.php.net/dtd/package-2.0                              http://pear.php.net/dtd/package-2.0.xsd">
 <name>pearweb_index</name>
 <channel>pear.php.net</channel>
 <summary>The source code for the PEAR website, informational front pages</summary>
 <description>The pearweb_index package contains these files from public_html:
 index.php, mirrors.php, credits.php, copyright.php, gophp5.php
 about/credits.php, about/index.php, about/privacy.php
 group/index.php and group/docs/*, news/*, and support/*
 </description>
 <lead>
  <name>Martin Jansen</name>
  <user>mj</user>
  <email>mj@php.net</email>
  <active>yes</active>
 </lead>
 <lead>
  <name>Greg Beaver</name>
  <user>cellog</user>
  <email>cellog@php.net</email>
  <active>yes</active>
 </lead>
 <lead>
  <name>David Coallier</name>
  <user>davidc</user>
  <email>davidc@php.net</email>
  <active>yes</active>
 </lead>
 <lead>
  <name>Pierre-Alain Joye</name>
  <user>pajoye</user>
  <email>pajoye@php.net</email>
  <active>no</active>
 </lead>
 <developer>
  <name>Stig Bakken</name>
  <user>ssb</user>
  <email>stig@php.net</email>
  <active>no</active>
 </developer>
 <developer>
  <name>Tomas V.V.Cox</name>
  <user>cox</user>
  <email>cox@idecnet.com</email>
  <active>no</active>
 </developer>
 <developer>
  <name>Daniel Convissor</name>
  <user>danielc</user>
  <email>danielc@php.net</email>
  <active>no</active>
 </developer>
 <developer>
  <name>Tobias Schlitt</name>
  <user>toby</user>
  <email>toby@php.net</email>
  <active>no</active>
 </developer>
 <developer>
  <name>Helgi Thormar</name>
  <user>dufuz</user>
  <email>dufuz@php.net</email>
  <active>yes</active>
 </developer>
 <developer>
  <name>Christian Weiske</name>
  <user>cweiske</user>
  <email>cweiske@php.net</email>
  <active>yes</active>
 </developer>
 <developer>
  <name>Mark Wiesemann</name>
  <user>wiesemann</user>
  <email>wiesemann@php.net</email>
  <active>yes</active>
 </developer>
 <date>2007-10-19</date>
 <version>
  <release>1.16.9</release>
  <api>1.0.0</api>
 </version>
 <stability>
  <release>stable</release>
  <api>stable</api>
 </stability>
 <license uri="http://www.php.net/license">PHP License</license>
 <notes>
 - Announce Planet PEAR
 </notes>
 <contents>
  <dir baseinstalldir="/" name="/">
   <dir name="public_html">
    <dir name="about">
     <file name="credits.php" role="web" />
     <file name="index.php" role="web" />
     <file name="privacy.php" role="web" />
    </dir> <!-- /public_html/about -->
    <dir name="group">
     <dir name="docs">
      <file name="20030820-vm.php" role="web" />
      <file name="20030904-pph.php" role="web" />
      <file name="20031114-bbr.php" role="web" />
      <file name="20031114-pcl.php" role="web" />
      <file name="20031114-pds.php" role="web" />
      <file name="20040226-vn.php" role="web" />
      <file name="20040322-vm.php" role="web" />
      <file name="20040402-la.php" role="web" />
      <file name="20051104-sa.php" role="web" />
      <file name="index.php" role="web" />
     </dir> <!-- /public_html/group/docs -->
     <file name="index.php" role="web" />
    </dir> <!-- /public_html/group -->
    <dir name="news">
     <file name="activestate-award-ssb.php" role="web" />
     <file name="group-announce.php" role="web" />
     <file name="index.php" role="web" />
     <file name="meeting-2003-summary.php" role="web" />
     <file name="meeting-2003.php" role="web" />
     <file name="newgroup-2007.php" role="web" />
     <file name="newpresident-2007.php" role="web" />
     <file name="nm-guide.php" role="web" />
     <file name="package.xml.1.0.php" role="web" />
     <file name="pecl-split.php" role="web" />
     <file name="pepr.php" role="web" />
     <file name="release-1.0.php" role="web" />
     <file name="vulnerability.php" role="web" />
     <file name="vulnerability2.php" role="web" />
     <file name="weekly-summaries.php" role="web" />
    </dir> <!-- /public_html/news -->
    <dir name="support">
     <file name="books.php" role="web" />
     <file name="effectivepearuse.php" role="web" />
     <file name="forums.php" role="web" />
     <file name="icons.php" role="web" />
     <file name="index.php" role="web" />
     <file name="lists.php" role="web" />
     <file name="pear.eps.gz" role="web" />
     <file name="slides.php" role="web" />
     <file name="tabs_list.php" role="web" />
     <file name="tutorials.php" role="web" />
    </dir> <!-- /public_html/support -->
    <file name="copyright.php" role="web" />
    <file name="credits.php" role="web" />
    <file name="faq.php" role="web" />
    <file name="index.php" role="web" />
    <file name="mirrors.php" role="web" />
    <file name="rest-login.php" role="web" />
    <file name="gophp5.php" role="web" />
   </dir> <!-- /public_html -->
  </dir> <!-- / -->
 </contents>
 <dependencies>
  <required>
   <php>
    <min>4.3.0</min>
   </php>
   <pearinstaller>
    <min>1.4.11</min>
   </pearinstaller>
  </required>
 </dependencies>
 <usesrole>
  <role>web</role>
  <package>Role_Web</package>
  <channel>pearified.com</channel>
 </usesrole>
 <phprelease />
 <changelog>
  <release>
   <version>
    <release>1.0.0RC1</release>
    <api>0.1.1</api>
   </version>
   <stability>
    <release>beta</release>
    <api>stable</api>
   </stability>
   <date>2007-06-01</date>
   <license uri="http://www.php.net/license">PHP License</license>
   <notes>
   initial split off of pearweb package
   </notes>
  </release>
  <release>
   <version>
    <release>1.0.0</release>
    <api>0.1.1</api>
   </version>
   <stability>
    <release>beta</release>
    <api>stable</api>
   </stability>
   <date>2007-06-01</date>
   <license uri="http://www.php.net/license">PHP License</license>
   <notes>
   initial split off of pearweb package
   </notes>
  </release>
  <release>
   <version>
    <release>1.16.1</release>
    <api>0.1.1</api>
   </version>
   <stability>
    <release>beta</release>
    <api>stable</api>
   </stability>
   <date>2007-06-02</date>
   <license uri="http://www.php.net/license">PHP License</license>
   <notes>
   Update news to include Paul Jone's election and addition of mirrors
   Use version number of pearweb to allow non-conflicting release tags
   </notes>
  </release>
  <release>
   <version>
    <release>1.16.2</release>
    <api>0.1.1</api>
   </version>
   <stability>
    <release>beta</release>
    <api>stable</api>
   </stability>
   <date>2007-06-02</date>
   <license uri="http://www.php.net/license">PHP License</license>
   <notes>
    Correct spelling of Paul Jones's last name on the PEAR group page (sigh...)
   </notes>
  </release>
  <release>
   <version>
    <release>1.16.3</release>
    <api>0.1.1</api>
   </version>
   <stability>
    <release>beta</release>
    <api>stable</api>
   </stability>
   <date>2007-06-04</date>
   <license uri="http://www.php.net/license">PHP License</license>
   <notes>
    Note that Josh Eichorn is the VP for 07-08
   </notes>
  </release>
  <release>
   <date>2007-06-09</date>
   <version>
    <release>1.16.4</release>
    <api>1.0.0</api>
   </version>
   <stability>
    <release>stable</release>
    <api>stable</api>
   </stability>
   <license uri="http://www.php.net/license">PHP License</license>
   <notes>
    Bug #11257 Wrong link tot Election results on mainpage news
   </notes>
  </release>
  <release>
   <date>2007-06-20</date>
   <version>
    <release>1.16.5</release>
    <api>1.0.0</api>
   </version>
   <stability>
    <release>stable</release>
    <api>stable</api>
   </stability>
   <license uri="http://www.php.net/license">PHP License</license>
   <notes>
    Add note about passing of Bertrand Gugger to homepage
    Add REST-based remote login validation
   </notes>
  </release>
  <release>
   <date>2007-06-20</date>
   <version>
    <release>1.16.6</release>
    <api>1.0.0</api>
   </version>
   <stability>
    <release>stable</release>
    <api>stable</api>
   </stability>
   <license uri="http://www.php.net/license">PHP License</license>
   <notes>
    Fix remote login code to use DB
   </notes>
  </release>
  <release>
   <date>2007-06-21</date>
   <version>
    <release>1.16.7</release>
    <api>1.0.0</api>
   </version>
   <stability>
    <release>stable</release>
    <api>stable</api>
   </stability>
   <license uri="http://www.php.net/license">PHP License</license>
   <notes>
    Add option for specifying required user karma, require registered users
    for remote login
   </notes>
  </release>
  <release>
   <date>2007-07-12</date>
   <version>
    <release>1.16.8</release>
    <api>1.0.0</api>
   </version>
   <stability>
    <release>stable</release>
    <api>stable</api>
   </stability>
   <license uri="http://www.php.net/license">PHP License</license>
   <notes>
   - Created a new page at /gophp5.php in order to be able to be accepted in the gophp5.org movement
   </notes>
  </release>
  <release>
   <date>2007-10-19</date>
   <version>
    <release>1.16.9</release>
    <api>1.0.0</api>
   </version>
   <stability>
    <release>stable</release>
    <api>stable</api>
   </stability>
   <license uri="http://www.php.net/license">PHP License</license>
   <notes>
   - announce planet pear
   </notes>
  </release>
 </changelog>
</package>
